name: Create Release
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore:')"

    steps:
    - uses: actions/checkout@v2

    - name: Create release
      run: |
        sh ./scripts/release.sh ${{ secrets.GITHUB_TOKEN }}
